package com.dreammaster.item;

import com.dreammaster.creativetab.ModTabList;
import com.dreammaster.main.MainRegistry;
import com.dreammaster.Tags;
import eu.usrv.yamcore.items.ModItemManager;
import eu.usrv.yamcore.items.ModSimpleBaseItem;
import net.minecraft.item.ItemStack;

public enum ItemList
{
    MicaBasedPulp(new ModSimpleBaseItem("MicaBasedPulp", ModTabList.ModGenericTab)),
    MicaBasedSheet(new ModSimpleBaseItem("MicaBasedSheet", ModTabList.ModGenericTab)),
    MicaInsulatorSheet(new ModSimpleBaseItem("MicaInsulatorSheet", ModTabList.ModGenericTab)),
    MicaInsulatorFoil(new ModSimpleBaseItem("MicaInsulatorFoil", ModTabList.ModGenericTab)),
    TenKCell(new ModSimpleBaseItem("TenKCell", ModTabList.ModGenericTab)),
    ThirtyKCell(new ModSimpleBaseItem("ThirtyKCell", ModTabList.ModGenericTab)),
    SixtyKCell(new ModSimpleBaseItem("SixtyKCell", ModTabList.ModGenericTab)),
    Empty180SpCell(new ModSimpleBaseItem("Empty180SpCell", ModTabList.ModGenericTab)),
    Empty360SpCell(new ModSimpleBaseItem("Empty360SpCell", ModTabList.ModGenericTab)),
    Empty540SpCell(new ModSimpleBaseItem("Empty540SpCell", ModTabList.ModGenericTab)),
    Empty1080SpCell(new ModSimpleBaseItem("Empty1080SpCell", ModTabList.ModGenericTab)),
    AluminiumBars(new ModSimpleBaseItem("AluminiumBars", ModTabList.ModBarsAndCasingsTab)),
    AluminiumItemCasing(new ModSimpleBaseItem("AluminiumItemCasing", ModTabList.ModBarsAndCasingsTab)),
    AluminiumIronPlate(new ModSimpleBaseItem("AluminiumIronPlate", ModTabList.ModSolarTab)),
    AlumiteDust(new ModSimpleBaseItem("AlumiteDust", ModTabList.ModGenericTab)),
    AdvancedCokeOvenBrick(new ModSimpleBaseItem("AdvancedCokeOvenBrick", ModTabList.ModGenericTab)),
    AdvancedCokeOvenBrickDust(new ModSimpleBaseItem("AdvancedCokeOvenBrickDust", ModTabList.ModGenericTab)),
    ApprenticeOrb(new ModSimpleBaseItem("ApprenticeOrb", ModTabList.ModThaumcraftTab)),
    ArcaneSlate(new ModSimpleBaseItem("ArcaneSlate", ModTabList.ModThaumcraftTab)),
    ArchmageOrb(new ModSimpleBaseItem("ArchmageOrb", ModTabList.ModThaumcraftTab)),
    ArcaneShardChip(new ModSimpleBaseItem("ArcaneShardChip", ModTabList.ModGenericTab)),
    ArcaneShardFragment(new ModSimpleBaseItem("ArcaneShardFragment", ModTabList.ModGenericTab)),
    ArditePlate(new ModSimpleBaseItem("ArditePlate", ModTabList.ModGenericTab)),
    ArtificialLeather(new ModSimpleBaseItem("ArtificialLeather", ModTabList.ModGenericTab)),
    BedrockiumPlate(new ModSimpleBaseItem("BedrockiumPlate", ModTabList.ModGenericTab)),
    BioCarbonPlate(new ModSimpleBaseItem("BioCarbonPlate", ModTabList.ModGenericTab)),
    BedrockiumIronPlate(new ModSimpleBaseItem("BedrockiumIronPlate", ModTabList.ModSolarTab)),
    BioBall(new ModSimpleBaseItem("BioBall", ModTabList.ModGenericTab)),
    BioOrganicMesh(new ModSimpleBaseItem("BioOrganicMesh", ModTabList.ModGenericTab)),
    BioChunk(new ModSimpleBaseItem("BioChunk", ModTabList.ModGenericTab)),
    Blaster(new ModSimpleBaseItem("Blaster", ModTabList.ModThaumcraftTab)),
    BloodVial(new ModSimpleBaseItem("BloodVial", ModTabList.ModThaumcraftTab)),
    BowFletchingCast(new ModSimpleBaseItem("BowFletchingCast", ModTabList.ModMoldsTab)),
    BowStringCast(new ModSimpleBaseItem("BowStringCast", ModTabList.ModMoldsTab)),
    CompressedBioBall(new ModSimpleBaseItem("CompressedBioBall", ModTabList.ModGenericTab)),
    CarminiteChip(new ModSimpleBaseItem("CarminiteChip", ModTabList.ModThaumcraftTab)),
    CarminiteFragment(new ModSimpleBaseItem("CarminiteFragment", ModTabList.ModThaumcraftTab)),
    ChargedMechanistWandCap(new ModSimpleBaseItem("ChargedMechanistWandCap", ModTabList.ModThaumcraftTab)),
    ChargedSilverWandCap(new ModSimpleBaseItem("ChargedSilverWandCap", ModTabList.ModThaumcraftTab)),
    ChargedSojournerWandCap(new ModSimpleBaseItem("ChargedSojournerWandCap", ModTabList.ModThaumcraftTab)),
    ChargedThaumiumWandCap(new ModSimpleBaseItem("ChargedThaumiumWandCap", ModTabList.ModThaumcraftTab)),
    ChargedVoidWandCap(new ModSimpleBaseItem("ChargedVoidWandCap", ModTabList.ModThaumcraftTab)),
    ChargedCertusQuartzDust(new ModSimpleBaseItem("ChargedCertusQuartzDust", ModTabList.ModGenericTab)),
    ChargedCertusQuartzPlate(new ModSimpleBaseItem("ChargedCertusQuartzPlate", ModTabList.ModGenericTab)),
    ChargedCertusQuartzRod(new ModSimpleBaseItem("ChargedCertusQuartzRod", ModTabList.ModGenericTab)),
    CokeOvenBrick(new ModSimpleBaseItem("CokeOvenBrick", ModTabList.ModGenericTab)),
    CokeOvenBrickDust(new ModSimpleBaseItem("CokeOvenBrickDust", ModTabList.ModGenericTab)),
    ConductiveIronBars(new ModSimpleBaseItem("ConductiveIronBars", ModTabList.ModBarsAndCasingsTab)),
    ChromeBars(new ModSimpleBaseItem("ChromeBars", ModTabList.ModBarsAndCasingsTab)),
    ChromeItemCasing(new ModSimpleBaseItem("ChromeItemCasing", ModTabList.ModBarsAndCasingsTab)),
    ChromeIronPlate(new ModSimpleBaseItem("ChromeIronPlate", ModTabList.ModSolarTab)),
    CobbleStoneRod(new ModSimpleBaseItem("CobbleStoneRod", ModTabList.ModGenericTab)),
    CopperWandCap(new ModSimpleBaseItem("CopperWandCap", ModTabList.ModThaumcraftTab)),
    CrimsonStainedClothCap(new ModSimpleBaseItem("CrimsonStainedClothCap", ModTabList.ModThaumcraftTab)),
    DraconiumEgg(new ModSimpleBaseItem("DraconiumEgg", ModTabList.ModGenericTab)),
    DiamondDrillTip(new ModSimpleBaseItem("DiamondDrillTip", ModTabList.ModGenericTab)),
    EctoplasmaChip(new ModSimpleBaseItem("EctoplasmaChip", ModTabList.ModGenericTab)),
    EctoplasmaFragment(new ModSimpleBaseItem("EctoplasmaFragment", ModTabList.ModGenericTab)),
    ElectricalSteelBars(new ModSimpleBaseItem("ElectricalSteelBars", ModTabList.ModBarsAndCasingsTab)),
    ElectricBoatHull(new ModSimpleBaseItem("ElectricBoatHull", ModTabList.ModGenericTab)),
    ElectrotineWire(new ModSimpleBaseItem("ElectrotineWire", ModTabList.ModGenericTab)),
    EMT(new ModSimpleBaseItem("EMT", ModTabList.ModGenericTab)),
    EnchantedClothCap(new ModSimpleBaseItem("EnchantedClothCap", ModTabList.ModThaumcraftTab)),
    EnderiumBaseBars(new ModSimpleBaseItem("EnderiumBaseBars", ModTabList.ModBarsAndCasingsTab)),
    EnderiumBars(new ModSimpleBaseItem("EnderiumBars", ModTabList.ModBarsAndCasingsTab)),
    EnergeticAlloyBars(new ModSimpleBaseItem("EnergeticAlloyBars", ModTabList.ModBarsAndCasingsTab)),
    EnderEgg(new ModSimpleBaseItem("EnderEgg", ModTabList.ModGenericTab)),
    EngineCore(new ModSimpleBaseItem("EngineCore", ModTabList.ModGenericTab)),
    EnrichedNaquadriaSunnariumAlloy(new ModSimpleBaseItem("EnrichedNaquadriaSunnariumAlloy", ModTabList.ModSolarTab)),
    EnrichedNaquadriaNeutroniumSunnariumAlloy(new ModSimpleBaseItem("EnrichedNaquadriaNeutroniumSunnariumAlloy", ModTabList.ModSolarTab)),
    EnrichedXSunnariumAlloy(new ModSimpleBaseItem("EnrichedXSunnariumAlloy", ModTabList.ModSolarTab)),
    ExtruderShapeBoat(new ModSimpleBaseItem("ExtruderShapeBoat", ModTabList.ModShapesTab)),
    FieryBloodDrop(new ModSimpleBaseItem("FieryBloodDrop", ModTabList.ModThaumcraftTab)),
    GlowingMarshmallow(new ModSimpleBaseItem("GlowingMarshmallow", ModTabList.ModThaumcraftTab)),
    GoldWandCap(new ModSimpleBaseItem("GoldWandCap", ModTabList.ModThaumcraftTab)),
    IchoriumCap(new ModSimpleBaseItem("IchoriumCap", ModTabList.ModThaumcraftTab)),
    IndustryFrame(new ModSimpleBaseItem("IndustryFrame", ModTabList.ModGenericTab)),
    InfernalBrick(new ModSimpleBaseItem("InfernalBrick", ModTabList.ModGenericTab)),
    IridiumItemCasing(new ModSimpleBaseItem("IridiumItemCasing", ModTabList.ModBarsAndCasingsTab)),
    IridiumBars(new ModSimpleBaseItem("IridiumBars", ModTabList.ModBarsAndCasingsTab)),
    IridiumAlloyItemCasing(new ModSimpleBaseItem("IridiumAlloyItemCasing", ModTabList.ModBarsAndCasingsTab)),
    IrradiantReinforcedAluminiumPlate(new ModSimpleBaseItem("IrradiantReinforcedAluminiumPlate", ModTabList.ModSolarTab)),
    IrradiantReinforcedBedrockiumPlate(new ModSimpleBaseItem("IrradiantReinforcedBedrockiumPlate", ModTabList.ModSolarTab)),
    IrradiantReinforcedChromePlate(new ModSimpleBaseItem("IrradiantReinforcedChromePlate", ModTabList.ModSolarTab)),
    IrradiantReinforcedNaquadriaPlate(new ModSimpleBaseItem("IrradiantReinforcedNaquadriaPlate", ModTabList.ModSolarTab)),
    IrradiantReinforcedNeutroniumPlate(new ModSimpleBaseItem("IrradiantReinforcedNeutroniumPlate", ModTabList.ModSolarTab)),
    IrradiantReinforcedTitaniumPlate(new ModSimpleBaseItem("IrradiantReinforcedTitaniumPlate", ModTabList.ModSolarTab)),
    IrradiantReinforcedTungstenPlate(new ModSimpleBaseItem("IrradiantReinforcedTungstenPlate", ModTabList.ModSolarTab)),
    IrradiantReinforcedTungstenSteelPlate(new ModSimpleBaseItem("IrradiantReinforcedTungstenSteelPlate", ModTabList.ModSolarTab)),
    IronWandCap(new ModSimpleBaseItem("IronWandCap", ModTabList.ModThaumcraftTab)),
    HotNetherrackBrick(new ModSimpleBaseItem("HotNetherrackBrick", ModTabList.ModGenericTab)),
    LapotronDust(new ModSimpleBaseItem("LapotronDust", ModTabList.ModCircuitsTab)),
    LaserEmitter(new ModSimpleBaseItem("LaserEmitter", ModTabList.ModGenericTab)),
    LichBone(new ModSimpleBaseItem("LichBone", ModTabList.ModThaumcraftTab)),
    LichBoneChip(new ModSimpleBaseItem("LichBoneChip", ModTabList.ModThaumcraftTab)),
    LichBoneFragment(new ModSimpleBaseItem("LichBoneFragment", ModTabList.ModThaumcraftTab)),
    LongObsidianRod(new ModSimpleBaseItem("LongObsidianRod", ModTabList.ModGenericTab)),
    LongStoneRod(new ModSimpleBaseItem("LongStoneRod", ModTabList.ModGenericTab)),
    MagicianOrb(new ModSimpleBaseItem("MagicianOrb", ModTabList.ModThaumcraftTab)),
    ManyullynPlate(new ModSimpleBaseItem("ManyullynPlate", ModTabList.ModGenericTab)),
    MaceratedPlantmass(new ModSimpleBaseItem("MaceratedPlantmass", ModTabList.ModGenericTab)),
    MalformedSlush(new ModSimpleBaseItem("MalformedSlush", ModTabList.ModThaumcraftTab)),
    Marshmallow(new ModSimpleBaseItem("Marshmallow", ModTabList.ModThaumcraftTab)),
    ManyullynCrystal(new ModSimpleBaseItem("ManyullynCrystal", ModTabList.ModGenericTab)),
    MarshmallowForm(new ModSimpleBaseItem("MarshmallowForm", ModTabList.ModThaumcraftTab)),
    MarshmallowFormMold(new ModSimpleBaseItem("MarshmallowFormMold", ModTabList.ModThaumcraftTab)),
    MasterOrb(new ModSimpleBaseItem("MasterOrb", ModTabList.ModThaumcraftTab)),
    MoldChestplate(new ModSimpleBaseItem("MoldChestplate", ModTabList.ModMoldsTab)),
    MoldHelmet(new ModSimpleBaseItem("MoldHelmet", ModTabList.ModMoldsTab)),
    MoldLeggings(new ModSimpleBaseItem("MoldLeggings", ModTabList.ModMoldsTab)),
    MoldFormLeggings(new ModSimpleBaseItem("MoldFormLeggings", ModTabList.ModMoldsTab)),
    MoldFormHelmet(new ModSimpleBaseItem("MoldFormHelmet", ModTabList.ModMoldsTab)),
    MoldFormChestplate(new ModSimpleBaseItem("MoldFormChestplate", ModTabList.ModMoldsTab)),
    MoldFormBoots(new ModSimpleBaseItem("MoldFormBoots", ModTabList.ModMoldsTab)),
    MoldBoots(new ModSimpleBaseItem("MoldBoots", ModTabList.ModMoldsTab)),
    MoldFormAnvil(new ModSimpleBaseItem("MoldFormAnvil", ModTabList.ModMoldsTab)),
    MoldFormArrowHead(new ModSimpleBaseItem("MoldFormArrowHead", ModTabList.ModMoldsTab)),
    MoldFormBaguette(new ModSimpleBaseItem("MoldFormBaguette", ModTabList.ModMoldsTab)),
    MoldFormBall(new ModSimpleBaseItem("MoldFormBall", ModTabList.ModMoldsTab)),
    MoldFormBlock(new ModSimpleBaseItem("MoldFormBlock", ModTabList.ModMoldsTab)),
    MoldFormBolt(new ModSimpleBaseItem("MoldFormBolt", ModTabList.ModMoldsTab)),
    MoldFormBottle(new ModSimpleBaseItem("MoldFormBottle", ModTabList.ModMoldsTab)),
    MoldFormBread(new ModSimpleBaseItem("MoldFormBread", ModTabList.ModMoldsTab)),
    MoldFormBuns(new ModSimpleBaseItem("MoldFormBuns", ModTabList.ModMoldsTab)),
    MoldFormCasing(new ModSimpleBaseItem("MoldFormCasing", ModTabList.ModMoldsTab)),
    MoldFormCoinage(new ModSimpleBaseItem("MoldFormCoinage", ModTabList.ModMoldsTab)),
    MoldFormCylinder(new ModSimpleBaseItem("MoldFormCylinder", ModTabList.ModMoldsTab)),
    MoldFormGear(new ModSimpleBaseItem("MoldFormGear", ModTabList.ModMoldsTab)),
    MoldFormIngot(new ModSimpleBaseItem("MoldFormIngot", ModTabList.ModMoldsTab)),
    MoldFormName(new ModSimpleBaseItem("MoldFormName", ModTabList.ModMoldsTab)),
    MoldFormNuggets(new ModSimpleBaseItem("MoldFormNuggets", ModTabList.ModMoldsTab)),
    MoldFormPlate(new ModSimpleBaseItem("MoldFormPlate", ModTabList.ModMoldsTab)),
    MoldFormRing(new ModSimpleBaseItem("MoldFormRing", ModTabList.ModMoldsTab)),
    MoldFormRound(new ModSimpleBaseItem("MoldFormRound", ModTabList.ModMoldsTab)),
    MoldFormRotor(new ModSimpleBaseItem("MoldFormRotor", ModTabList.ModMoldsTab)),
    MoldFormScrew(new ModSimpleBaseItem("MoldFormScrew", ModTabList.ModMoldsTab)),
    MoldFormSmallGear(new ModSimpleBaseItem("MoldFormSmallGear", ModTabList.ModMoldsTab)),
    MoldFormStick(new ModSimpleBaseItem("MoldFormStick", ModTabList.ModMoldsTab)),
    MoldFormStickLong(new ModSimpleBaseItem("MoldFormStickLong", ModTabList.ModMoldsTab)),
    MoldFormTurbineBlade(new ModSimpleBaseItem("MoldFormTurbineBlade", ModTabList.ModMoldsTab)),
    MoldFormPipeTiny(new ModSimpleBaseItem("MoldFormPipeTiny", ModTabList.ModMoldsTab)),
    MoldFormPipeSmall(new ModSimpleBaseItem("MoldFormPipeSmall", ModTabList.ModMoldsTab)),
    MoldFormPipeMedium(new ModSimpleBaseItem("MoldFormPipeMedium", ModTabList.ModMoldsTab)),
    MoldFormPipeLarge(new ModSimpleBaseItem("MoldFormPipeLarge", ModTabList.ModMoldsTab)),
    MoldFormPipeHuge(new ModSimpleBaseItem("MoldFormPipeHuge", ModTabList.ModMoldsTab)),
    MoonStoneDust(new ModSimpleBaseItem("MoonStoneDust", ModTabList.ModGenericTab)),
    MushroomPowder(new ModSimpleBaseItem("MushroomPowder", ModTabList.ModGenericTab)),
    MutatedEgg(new ModSimpleBaseItem("MutatedEgg", ModTabList.ModGenericTab)),
    NagaScaleChip(new ModSimpleBaseItem("NagaScaleChip", ModTabList.ModThaumcraftTab)),
    NagaScaleFragment(new ModSimpleBaseItem("NagaScaleFragment", ModTabList.ModThaumcraftTab)),
    NaquadriaIronPlate(new ModSimpleBaseItem("NaquadriaIronPlate", ModTabList.ModSolarTab)),
    NeutroniumBars(new ModSimpleBaseItem("NeutroniumBars", ModTabList.ModBarsAndCasingsTab)),
    NeutroniumItemCasing(new ModSimpleBaseItem("NeutroniumItemCasing", ModTabList.ModBarsAndCasingsTab)),
    NeutroniumIronPlate(new ModSimpleBaseItem("NeutroniumIronPlate", ModTabList.ModSolarTab)),
    NeutronReflectorSmallParts(new ModSimpleBaseItem("NeutronReflectorSmallParts", ModTabList.ModCircuitsTab)),
    NeutronReflectorParts(new ModSimpleBaseItem("NeutronReflectorParts", ModTabList.ModCircuitsTab)),
    NetherStarFragment(new ModSimpleBaseItem("NetherStarFragment", ModTabList.ModGenericTab)),
    Nothing(new ModSimpleBaseItem("Nothing", ModTabList.ModGenericTab)),
    PotassiumHydroxideDust(new ModSimpleBaseItem("PotassiumHydroxideDust", ModTabList.ModGenericTab)),
    PrimordialPearlFragment(new ModSimpleBaseItem("PrimordialPearlFragment", ModTabList.ModThaumcraftTab)),
    PulsatingIronBars(new ModSimpleBaseItem("PulsatingIronBars", ModTabList.ModBarsAndCasingsTab)),
    OsmiumItemCasing(new ModSimpleBaseItem("OsmiumItemCasing", ModTabList.ModBarsAndCasingsTab)),
    OsmiumBars(new ModSimpleBaseItem("OsmiumBars", ModTabList.ModBarsAndCasingsTab)),
    RawBioFiber(new ModSimpleBaseItem("RawBioFiber", ModTabList.ModGenericTab)),
    RawLapotronCrystal(new ModSimpleBaseItem("RawLapotronCrystal", ModTabList.ModCircuitsTab)),
    RawOrbTier1(new ModSimpleBaseItem("RawOrbTier1", ModTabList.ModThaumcraftTab)),
    RawOrbTier2(new ModSimpleBaseItem("RawOrbTier2", ModTabList.ModThaumcraftTab)),
    RawOrbTier3(new ModSimpleBaseItem("RawOrbTier3", ModTabList.ModThaumcraftTab)),
    RawOrbTier4(new ModSimpleBaseItem("RawOrbTier4", ModTabList.ModThaumcraftTab)),
    RawOrbTier5(new ModSimpleBaseItem("RawOrbTier5", ModTabList.ModThaumcraftTab)),
    RawOrbTier6(new ModSimpleBaseItem("RawOrbTier6", ModTabList.ModThaumcraftTab)),
    RedstoneAlloyBars(new ModSimpleBaseItem("RedstoneAlloyBars", ModTabList.ModBarsAndCasingsTab)),
    ReinforcedGlassPlate(new ModSimpleBaseItem("ReinforcedGlassPlate", ModTabList.ModGenericTab)),
    ReinforcedGlassLense(new ModSimpleBaseItem("ReinforcedGlassLense", ModTabList.ModGenericTab)),
    ReinforcedIridiumDrillTip(new ModSimpleBaseItem("ReinforcedIridiumDrillTip", ModTabList.ModGenericTab)),
    ReinforcedAluminiumIronPlate(new ModSimpleBaseItem("ReinforcedAluminiumIronPlate", ModTabList.ModSolarTab)),
    ReinforcedBedrockiumIronPlate(new ModSimpleBaseItem("ReinforcedBedrockiumIronPlate", ModTabList.ModSolarTab)),
    ReinforcedChromeIronPlate(new ModSimpleBaseItem("ReinforcedChromeIronPlate", ModTabList.ModSolarTab)),
    ReinforcedNaquadriaIronPlate(new ModSimpleBaseItem("ReinforcedNaquadriaIronPlate", ModTabList.ModSolarTab)),
    ReinforcedNeutroniumIronPlate(new ModSimpleBaseItem("ReinforcedNeutroniumIronPlate", ModTabList.ModSolarTab)),
    ReinforcedTitaniumIronPlate(new ModSimpleBaseItem("ReinforcedTitaniumIronPlate", ModTabList.ModSolarTab)),
    ReinforcedTungstenIronPlate(new ModSimpleBaseItem("ReinforcedTungstenIronPlate", ModTabList.ModSolarTab)),
    ReinforcedTungstenSteelIronPlate(new ModSimpleBaseItem("ReinforcedTungstenSteelIronPlate", ModTabList.ModSolarTab)),
    RuneOfPowerFragment(new ModSimpleBaseItem("RuneOfPowerFragment", ModTabList.ModGenericTab)),
    RuneOfAgilityFragment(new ModSimpleBaseItem("RuneOfAgilityFragment", ModTabList.ModGenericTab)),
    RuneOfVigorFragment(new ModSimpleBaseItem("RuneOfVigorFragment", ModTabList.ModGenericTab)),
    RuneOfDefenseFragment(new ModSimpleBaseItem("RuneOfDefenseFragment", ModTabList.ModGenericTab)),
    RuneOfMagicFragment(new ModSimpleBaseItem("RuneOfMagicFragment", ModTabList.ModGenericTab)),
    RuneOfVoidFragment(new ModSimpleBaseItem("RuneOfVoidFragment", ModTabList.ModGenericTab)),
    SandDust(new ModSimpleBaseItem("SandDust", ModTabList.ModGenericTab)),
    SandStoneRod(new ModSimpleBaseItem("SandStoneRod", ModTabList.ModGenericTab)),
    SawBladeStone(new ModSimpleBaseItem("SawBladeStone", ModTabList.ModGenericTab)),
    SawBladeDiamond(new ModSimpleBaseItem("SawBladeDiamond", ModTabList.ModGenericTab)),
    SawBladeArdite(new ModSimpleBaseItem("SawBladeArdite", ModTabList.ModGenericTab)),
    SawBladeManyullyn(new ModSimpleBaseItem("SawBladeManyullyn", ModTabList.ModGenericTab)),
    SawBladeRuby(new ModSimpleBaseItem("SawBladeRuby", ModTabList.ModGenericTab)),
    SawBladeSapphire(new ModSimpleBaseItem("SawBladeSapphire", ModTabList.ModGenericTab)),
    SawBladePeridot(new ModSimpleBaseItem("SawBladePeridot", ModTabList.ModGenericTab)),
    ShadowImbuedClothCap(new ModSimpleBaseItem("ShadowImbuedClothCap", ModTabList.ModThaumcraftTab)),
    ShadowmetalCap(new ModSimpleBaseItem("ShadowmetalCap", ModTabList.ModThaumcraftTab)),
    ShapeAxeHead(new ModSimpleBaseItem("ShapeAxeHead", ModTabList.ModShapesTab)),
    ShapeBlock(new ModSimpleBaseItem("ShapeBlock", ModTabList.ModShapesTab)),
    ShapeBoat(new ModSimpleBaseItem("ShapeBoat", ModTabList.ModShapesTab)),
    ShapeBolt(new ModSimpleBaseItem("ShapeBolt", ModTabList.ModShapesTab)),
    ShapeBottle(new ModSimpleBaseItem("ShapeBottle", ModTabList.ModShapesTab)),
    ShapeCasing(new ModSimpleBaseItem("ShapeCasing", ModTabList.ModShapesTab)),
    ShapeCell(new ModSimpleBaseItem("ShapeCell", ModTabList.ModShapesTab)),
    ShapeFileHead(new ModSimpleBaseItem("ShapeFileHead", ModTabList.ModShapesTab)),
    ShapeGear(new ModSimpleBaseItem("ShapeGear", ModTabList.ModShapesTab)),
    ShapeHammerHead(new ModSimpleBaseItem("ShapeHammerHead", ModTabList.ModShapesTab)),
    ShapeHoeHead(new ModSimpleBaseItem("ShapeHoeHead", ModTabList.ModShapesTab)),
    ShapeHugePipe(new ModSimpleBaseItem("ShapeHugePipe", ModTabList.ModShapesTab)),
    ShapeIngot(new ModSimpleBaseItem("ShapeIngot", ModTabList.ModShapesTab)),
    ShapeLargePipe(new ModSimpleBaseItem("ShapeLargePipe", ModTabList.ModShapesTab)),
    ShapeNormalPipe(new ModSimpleBaseItem("ShapeNormalPipe", ModTabList.ModShapesTab)),
    ShapePickaxeHead(new ModSimpleBaseItem("ShapePickaxeHead", ModTabList.ModShapesTab)),
    ShapePlate(new ModSimpleBaseItem("ShapePlate", ModTabList.ModShapesTab)),
    ShapeRing(new ModSimpleBaseItem("ShapeRing", ModTabList.ModShapesTab)),
    ShapeRod(new ModSimpleBaseItem("ShapeRod", ModTabList.ModShapesTab)),
    ShapeRotor(new ModSimpleBaseItem("ShapeRotor", ModTabList.ModShapesTab)),
    ShapeSawBlade(new ModSimpleBaseItem("ShapeSawBlade", ModTabList.ModShapesTab)),
    ShapeShovelHead(new ModSimpleBaseItem("ShapeShovelHead", ModTabList.ModShapesTab)),
    ShapeSmallGear(new ModSimpleBaseItem("ShapeSmallGear", ModTabList.ModShapesTab)),
    ShapeSmallPipe(new ModSimpleBaseItem("ShapeSmallPipe", ModTabList.ModShapesTab)),
    ShapeSwordBlade(new ModSimpleBaseItem("ShapeSwordBlade", ModTabList.ModShapesTab)),
    ShapeTinyPipe(new ModSimpleBaseItem("ShapeTinyPipe", ModTabList.ModShapesTab)),
    ShapeTurbineBlade(new ModSimpleBaseItem("ShapeTurbineBlade", ModTabList.ModShapesTab)),
    ShapeWire(new ModSimpleBaseItem("ShapeWire", ModTabList.ModShapesTab)),
    SilverThread(new ModSimpleBaseItem("SilverThread", ModTabList.ModThaumcraftTab)),
	SilveredFleece(new ModSimpleBaseItem("SilveredFleece", ModTabList.ModThaumcraftTab)),
    SnowQueenBlood(new ModSimpleBaseItem("SnowQueenBlood", ModTabList.ModThaumcraftTab)),
    SnowQueenBloodDrop(new ModSimpleBaseItem("SnowQueenBloodDrop", ModTabList.ModThaumcraftTab)),
    SoulariumBars(new ModSimpleBaseItem("SoulariumBars", ModTabList.ModBarsAndCasingsTab)),
    StainlessSteelBars(new ModSimpleBaseItem("StainlessSteelBars", ModTabList.ModBarsAndCasingsTab)),
    StainlessSteelItemCasing(new ModSimpleBaseItem("StainlessSteelItemCasing", ModTabList.ModBarsAndCasingsTab)),
    SteelBars(new ModSimpleBaseItem("SteelBars", ModTabList.ModBarsAndCasingsTab)),
    StonePlate(new ModSimpleBaseItem("StonePlate", ModTabList.ModGenericTab)),
    TeleposerFrame(new ModSimpleBaseItem("TeleposerFrame", ModTabList.ModThaumcraftTab)),
    TheBigEgg(new ModSimpleBaseItem("TheBigEgg", ModTabList.ModGenericTab)),
    TitaniumBars(new ModSimpleBaseItem("TitaniumBars", ModTabList.ModBarsAndCasingsTab)),
    TitaniumItemCasing(new ModSimpleBaseItem("TitaniumItemCasing", ModTabList.ModBarsAndCasingsTab)),
    TitaniumIronPlate(new ModSimpleBaseItem("TitaniumIronPlate", ModTabList.ModSolarTab)),
    TranscendentOrb(new ModSimpleBaseItem("TranscendentOrb", ModTabList.ModThaumcraftTab)),
    TungstenBars(new ModSimpleBaseItem("TungstenBars", ModTabList.ModBarsAndCasingsTab)),
    TungstenItemCasing(new ModSimpleBaseItem("TungstenItemCasing", ModTabList.ModBarsAndCasingsTab)),
    TungstenIronPlate(new ModSimpleBaseItem("TungstenIronPlate", ModTabList.ModSolarTab)),
    TungstenSteelBars(new ModSimpleBaseItem("TungstenSteelBars", ModTabList.ModBarsAndCasingsTab)),
    TungstenSteelItemCasing(new ModSimpleBaseItem("TungstenSteelItemCasing", ModTabList.ModBarsAndCasingsTab)),
    TungstenSteeLIronPlate(new ModSimpleBaseItem("TungstenSteelIronPlate", ModTabList.ModSolarTab)),
    TwilightCrystal(new ModSimpleBaseItem("TwilightCrystal", ModTabList.ModGenericTab)),
    UncookedSlush(new ModSimpleBaseItem("UncookedSlush", ModTabList.ModThaumcraftTab)),
    UnfiredClayBrick(new ModSimpleBaseItem("UnfiredClayBrick", ModTabList.ModGenericTab)),
    UnfiredCokeOvenBrick(new ModSimpleBaseItem("UnfiredCokeOvenBrick", ModTabList.ModGenericTab)),
    UnfiredSearedBrick(new ModSimpleBaseItem("UnfiredSearedBrick", ModTabList.ModGenericTab)),
    UnfiredSlimeSoulBrick(new ModSimpleBaseItem("UnfiredSlimeSoulBrick", ModTabList.ModGenericTab)),
    VibrantAlloyBars(new ModSimpleBaseItem("VibrantAlloyBars", ModTabList.ModBarsAndCasingsTab)),
	VinteumThread(new ModSimpleBaseItem("VinteumThread", ModTabList.ModThaumcraftTab)),
    VoidEssence(new ModSimpleBaseItem("VoidEssence", ModTabList.ModThaumcraftTab)),
    VoidFoil(new ModSimpleBaseItem("VoidFoil", ModTabList.ModThaumcraftTab)),
    VoidPlate(new ModSimpleBaseItem("VoidPlate", ModTabList.ModThaumcraftTab)),
    VoidRing(new ModSimpleBaseItem("VoidRing", ModTabList.ModThaumcraftTab)),
    VoidRod(new ModSimpleBaseItem("VoidRod", ModTabList.ModThaumcraftTab)),
    VoidSeed(new ModSimpleBaseItem("VoidSeed", ModTabList.ModThaumcraftTab)),
    WandCapAlchemical(new ModSimpleBaseItem("WandCapAlchemical", ModTabList.ModThaumcraftTab)),
    WandCapBloodIron(new ModSimpleBaseItem("WandCapBloodIron", ModTabList.ModThaumcraftTab)),
    WandCapElementium(new ModSimpleBaseItem("WandCapElementium", ModTabList.ModThaumcraftTab)),
    WandCapManaSteel(new ModSimpleBaseItem("WandCapManaSteel", ModTabList.ModThaumcraftTab)),
    WandCapTerraSteel(new ModSimpleBaseItem("WandCapTerraSteel", ModTabList.ModThaumcraftTab)),
    WandCapVinteum(new ModSimpleBaseItem("WandCapVinteum", ModTabList.ModThaumcraftTab)),
    WandCapThauminite(new ModSimpleBaseItem("WandCapThauminite", ModTabList.ModThaumcraftTab)),
    WeakOrb(new ModSimpleBaseItem("WeakOrb", ModTabList.ModThaumcraftTab)),
    WetTofu(new ModSimpleBaseItem("WetTofu", ModTabList.ModGenericTab)),
    WirelessTransmitter(new ModSimpleBaseItem("WirelessTransmitter", ModTabList.ModGenericTab)),
    WoodenBrickForm(new ModSimpleBaseItem(new WoodenBrickFormProperties(), ModTabList.ModGenericTab)),
    WoodenCasing(new ModSimpleBaseItem("WoodenCasing", ModTabList.ModGenericTab)),
    MedalDerp(new ModSimpleBaseItem("MedalDerp", ModTabList.ModGenericTab)),
    MedalGTExplosion(new ModSimpleBaseItem("MedalGTExplosion", ModTabList.ModGenericTab)),
    MedalBuilder(new ModSimpleBaseItem("MedalBuilder", ModTabList.ModGenericTab)),
    MedalEngineer(new ModSimpleBaseItem("MedalEngineer", ModTabList.ModGenericTab)),
    MedalWarp(new ModSimpleBaseItem("MedalWarp", ModTabList.ModGenericTab)),
    AluminoSilicateWool(new ModSimpleBaseItem("AluminoSilicateWool", ModTabList.ModGenericTab)),
    EdibleSalt(new ModSimpleBaseItem("EdibleSalt", ModTabList.ModGenericTab)),

    // Do not delete this
    EndOfList(null);

    // ################################################################################
    public ModSimpleBaseItem Item;

    ItemList(ModSimpleBaseItem pItem)
    {
        Item = pItem;
        if (Item != null) {
            Item.setModIDName(Tags.MODID);
        }
    }

    public static boolean AddToItemManager(ModItemManager pItemManager)
    {
        boolean tResult = true;
        for (ItemList il : ItemList.values())
        {
            if (il.Item != null) {
                if (!pItemManager.AddItemToManagedRegistry(il.Item)) {
                    MainRegistry.Logger.error(String.format("Item [%s] failed to register", il.toString()));
                    tResult = false;
                }
            }
        }

        return tResult;
    }

    public ItemStack getIS()
    {
        return new ItemStack(Item.getConstructedItem(), 1);
    }
    
    public ItemStack getIS(int amount)
    {
        return new ItemStack(Item.getConstructedItem(), amount);
    }

}
